version: '3.3'

services:
  mongo:
    image: mongo:6.0.5
    container_name: 'rsww_mongo'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    networks:
      - net

  mysql:
    image: mysql:8.0.33
    container_name: 'rsww_mysql'
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - net

    reservations_db:
      image: mysql:8.0.33
      container_name: 'reservations_db'
      restart: always
      ports:
        - "3307:3306"
      environment:
        - MYSQL_ROOT_USER=root
        - MYSQL_ROOT_PASSWORD=root
      networks:
        - net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rsww_rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - net

networks:
  net:
    driver: bridge
