version: '3.4'

services:
  mongo:
    image: mongo:6.0.5
    container_name: 'rsww_mongo'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    networks:
      - net

  mysql:
    image: mysql:8.0.33
    container_name: 'rsww_mysql'
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rsww_rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - net

  transport_read:
    build:
      context: ./apps/transport
      dockerfile: Dockerfile
      target: transport-read-service-img
    container_name: 'rsww_transport_read'
    restart: always
    ports:
      - "9010:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/transport_read_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_FLYWAY_USER=root
      - SPRING_FLYWAY_PASSWORD=root
    networks:
      - net

  transport_write:
    build:
      context: ./apps/transport
      dockerfile: Dockerfile
      target: transport-write-service-img
    container_name: 'rsww_transport_write'
    restart: always
    ports:
      - "9011:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/transport_write_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_FLYWAY_USER=root
      - SPRING_FLYWAY_PASSWORD=root
    networks:
      - net

networks:
  net:
    driver: bridge
