version: '3.4'

services:

  nginx:
    container_name: 'rsww-gateway'
    image: bartoszdab/rsww-gateway
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5
        window: 60s
    ports:
      - '18007:80'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rsww_rabbitmq'
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5
        window: 60s
    ports:
      - "18009:5672"

  transportRead:
    image: bartoszdab/rsww-transport-read
    container_name: 'rsww_transport_read'
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5
        window: 60s
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://actina15.maas:5432/18007_transport_read_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=student
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=student

  transportWrite:
    image: bartoszdab/rsww-transport-write
    container_name: 'rsww_transport_write'
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5
        window: 60s
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://actina15.maas:5432/18007_transport_write_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=student
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=student

  paymentRead:
    image: bartoszdab/rsww-payment-read
    container_name: 'rsww_payment'
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5
        window: 60s
    environment:
      - SERVER_PORT=8080
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest

  reservationRead:
    image: bartoszdab/rsww-reservation-read
    container_name: 'rsww_reservation_read'
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5
        window: 60s
    environment:
      - SERVER_PORT=8080
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_DATA_MONGODB_HOST=actina15.maas
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=18007_reservations
      - SPRING_DATA_MONGODB_USERNAME=root
      - SPRING_DATA_MONGODB_PASSWORD=student
      - SERVICES_TRANSPORT_APIURL=http://transportRead:8080/api/transport/v1/read
      - SERVICES_HOTEL_APIURL=http://hotelRead:80/api/hotels/v1/read

  reservationWrite:
    image: bartoszdab/rsww-reservation-write
    container_name: 'rsww_reservation_write'
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5
        window: 60s
    environment:
      - SERVER_PORT=8080
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_DATA_MONGODB_HOST=actina15.maas
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=18007_reservation_events
      - SPRING_DATA_MONGODB_USERNAME=root
      - SPRING_DATA_MONGODB_PASSWORD=student

  hotelRead:
    image: grzegorestyty/rsww-hotel-api:latest
    container_name: 'rsww_hotel_read'
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5
        window: 60s
    environment:
      - RabbitMQOptions__HostName=rabbitmq
      - RabbitMQOptions__UserName=guest
      - RabbitMQOptions__Password=guest
      - RabbitMQOptions__Port=5672
      - RabbitMQOptions__VirtualHost=/
      - RabbitMQOptions__RetryIntervalSeconds=10

  hotelEventHandler:
    image: grzegorestyty/rsww-hotel-eventhandler:latest
    container_name: 'rsww_hotel_event_handler'
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5
        window: 60s

  hotelCommands:
    image: grzegorestyty/rsww-hotel-commands:latest
    container_name: 'rsww_hotel_commands'
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5
        window: 60s

  front:
    image: bartoszdab/rsww-front
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5
        window: 60s
    ports:
      - "18008:8080"

