name: Build and push reservation service images

on:
  push:
    branches: [ "main" ]
    paths:
    - apps/ReservationService/**

jobs:

# TODO: Update after adding hotel read service
#  build_hotel_read:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v3
#    - name: Build and push hotel read service image
#      env:
#        DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
#        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#      run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD && cd apps/hotel && docker build --target reservation-read-service -t bartoszdab/rsww-reservation-read:latest . && docker push bartoszdab/rsww-reservation-read:latest

  build_hotel_write:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push hotel write service image
      env:
        DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD && cd apps/hotel && docker build -t bartoszdab/rsww-hotel-write:latest . && docker push bartoszdab/rsww-hotel-write:latest
