name: Build and push gateway image

on:
  push:
    branches: [ "main" ]
    paths:
    - apps/Gateway/**

jobs:

  build_gateway:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push gateway image
      env:
        DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD && cd apps/Gateway && docker build -t bartoszdab/rsww-gateway:latest . && docker push bartoszdab/rsww-gateway:latest
